### PR TITLE
Added Rabs AP% passive, fixed Mpen% to percent, Mpenflat to flat, rpen% to percent instead of flat

### PR DESCRIPTION
**Pull request by vorpal56**
Added dependencies in requirements.txt and extended docs with installation and running.

Item changes:
1. Rabadon's Deathcap was missing the increased ability power percent in passive stats object, so added to passive stats
2. Mpenflat is missing from Sorc shoes and Ludens Tempest
3. Mpen% missing from Voidstaff and Blighting Jewel
4. Apen% is now mapped to percent instead of flat on Lord Dominiks Regard, Last Whisper, and Serylda's Grudge
5. AS% for regular stats is now mapped to percent instead of flat eg. Trinity Force, Kraken Slayer, etc.

### CODE REVIEW

**Comment by jjmaldonis** [comment]
Most of this looks good. These are fine:
* .gitignore
* adding ability power percent
* changing armor pen to percent
* magic pen changes

There are a couple newlines deleted in lines 608 and 609 in `pull_items_wiki.py` that look like they should be there.

The attack speed should be flat, not percent.

For the `requirements.txt`, we don't need all the packages - only the ones that are actually used. This is what I don't like about `pip freeze`, it prints all the packages, not just the top-level ones that are needed. We also don't need the versions. If packages get bugfixed, I want those updates to be applied. The only real way to create a good `requirements.txt` is to look through all the imports and find the corresponding pip packages to install.

**Comment by vorpal56** [comment]
Should I add the newlines back into `pull_items_wiki.py`?

Attack speed on item **regular stats** are percent, while item **passive stats** are set to flat. This is to keep consistent with the model of attack speed being a percent stat and not a percent and flat stat across the entire `Item` model.

The `requirements.txt` is just the content that is needed to run the code. I first cloned and created a virtual environment (why I added environments in `.gitignore`) without any packages and added packages when it threw an exception while attempting to run. When packages get updated, you can update the required package while the virtual environment is activated.

**Comment by jjmaldonis** [comment]
Yeah, add the newlines back to `pull_items_wiki.py`. Even better, the autoformatter `black` with linelength=120 can be used to ensure the files are formatted properly.

You're going to have to give me some more info on the attack speed stuff. I put quite a lot of time into this and while I haven't been paying much attention lately, I doubt Riot made sweep changes to how they calculate and apply attack speed modifiers during the preseason changes. I may be wrong, but I need much more info before I can merge that change.

For the `requirements.txt`, remove the versions and only include the packages that are imported in this library, not packages that are dependencies of other packages (like certifi).

**Comment by vorpal56** [comment]
Added the newlines back to `pull_items_wiki.py` with the `black` autoformatter and `linelength=120`.

Looking at the attack speed formula, items, runes, and champion ability modifiers (eg. Fiora [E] Bladework) are on an additive basis (flat) and then multiplied back with champion's base attack speed. The general formula for attack speed: 
```
AS = AS_BASE * (1 + (StatsGrowthFormula(as_per_level, champion_level) + items + runes + champion_modifiers) / 100)
```
Then the item regular stats for attack speed should stay flat instead of percent, and passive stats for attack speed should be flat instead of percent. I haven't made any changes, but I'm pretty sure that's what it's supposed to be.

I brought it up since the the template for Item Wiki data has the description of attack speed as percent, so my understanding would be percent instead of flat.

**Comment by jjmaldonis** [comment]
Fantastic! Thanks for putting all the time and effort into this work and this PR. It looks great. I think you are dead on with the attack speed, and it's looking good now. Anyone who uses it will have to create a custom formula for it as well.

**Pull request merged**
